server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  application:
    name: resource-server
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          #jwk-set-uri: http://localhost:8190/realms/dev%20realm/protocol/openid-connect/certs # The URI used to retrieve the JSON Web Key (JWK) Set from the Authorization Server, which contains the cryptographic key(s) used to verify the JSON Web Signature (JWS) of the ID Token and (optionally) the UserInfo Response.

group:
  id: Banking-API-DEV

jasypt:
  encryptor:
    password: FILE:../secret_key.b64
    #Optional, defaults to 0, no salt. If provided, specify the salt string in ba64 format
    salt: c3NwaXRfc2FsdF9zd2VldAo=
    algorithm: AES/GCM/NoPadding
    secretKeyAlgorithm: PBKDF2WithHmacSHA256

security:
  truststore: classpath:config/prod/keystore/client-truststore.p12
  truststorePassword: ENC(lrfd4eZ2fztVo1XUip9qJCuOgW2NLF5+HT6A6eOXoU6rritw)