server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  application:
    name: auth-server
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


datasource:
  auth-server:
    jdbc-url: jdbc:mysql://localhost:3306/${spring.application.name}
    username: security
    password: security123456