server:
  port: 8081

spring:
  application:
    name: security-lab
  profiles:
    active: default
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 442417568524-6df9ulgfc8ire1eo0r1smmgc42aaq3pe.apps.googleusercontent.com
            client-secret: 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
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: openid,profile,email
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            issuer-uri: https://accounts.google.com
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-info-authentication-method: header
            user-name-attribute: sub

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

datasource:
  deepblue:
    jdbc-url: jdbc:mysql://localhost:3306/deepblue
    username: deepblue
    password: deepblue123456


